home:
    path: adminlte_welcome
# Employees
index:
    path: /
    controller: App\Controller\EmployeeController::index

list_employees:
    path: /empleado/lista
    controller: App\Controller\EmployeeController::index

show_form:
    path: /empleado/registro/{id}
    controller: App\Controller\EmployeeController::showForm
    defaults:
        id: null

create_employee:
    path: /empleado/crear
    controller: App\Controller\EmployeeController::create
    methods: POST

update_employee:
    path: /empleado/actualizar/{id}
    controller: App\Controller\EmployeeController::update
    methods: [POST]

delete_employee:
    path: /empleado/eliminar/{id}
    controller: App\Controller\EmployeeController::delete
    methods: [GET]

# Customers   
list_customer:
    path: /cliente/lista
    controller: App\Controller\CustomerController::index

show_form_customer:
    path: /cliente/registro/{id}
    controller: App\Controller\CustomerController::showForm
    defaults:
        id: null

create_customer:
    path: /cliente/crear
    controller: App\Controller\CustomerController::create
    methods: POST

update_customer:
    path: /cliente/actualizar/{id}
    controller: App\Controller\CustomerController::update
    methods: [POST]

delete_customer:
    path: /cliente/eliminar/{id}
    controller: App\Controller\CustomerController::delete
    methods: [GET]

#Products
list_product:
    path: /productos/lista
    controller: App\Controller\ProductController::index

show_form_product:
    path: /producto/registro/{id}
    controller: App\Controller\ProductController::showForm
    defaults:
        id: null

create_product:
    path: /producto/crear
    controller: App\Controller\ProductController::create
    methods: POST

update_product:
    path: /producto/actualizar/{id}
    controller: App\Controller\ProductController::update
    methods: [POST]

delete_product:
    path: /producto/eliminar/{id}
    controller: App\Controller\ProductController::delete
    methods: [GET]

#ShopGroups
list_shopgroup:
    path: /shopgroup/lista
    controller: App\Controller\ShopGroupController::index

show_form_shopgroup:
    path: /shopgroup/registro/{id}
    controller: App\Controller\ShopGroupController::showForm
    defaults:
        id: null

create_shopgroup:
    path: /shopgroup/crear
    controller: App\Controller\ShopGroupController::create
    methods: POST

update_shopgroup:
    path: /shopgroup/actualizar/{id}
    controller: App\Controller\ShopGroupController::update
    methods: [POST]

delete_shopgroup:
    path: /shopgroup/eliminar/{id}
    controller: App\Controller\ShopGroupController::delete
    methods: [GET]

#ShopSeries
list_shopseries:
    path: /shopseries/lista
    controller: App\Controller\ShopSeriesController::index

show_form_shopseries:
    path: /shopseries/registro/{id}
    controller: App\Controller\ShopSeriesController::showForm
    defaults:
        id: null

create_shopseries:
    path: /shopseries/crear
    controller: App\Controller\ShopSeriesController::create
    methods: POST

update_shopseries:
    path: /shopseries/actualizar/{id}
    controller: App\Controller\ShopSeriesController::update
    methods: [POST]

delete_shopseries:
    path: /shopseries/eliminar/{id}
    controller: App\Controller\ShopSeriesController::delete
    methods: [GET]

#Shops
list_shop:
    path: /tienda/lista
    controller: App\Controller\ShopController::index

show_form_shop:
    path: /tienda/registro/{id}
    controller: App\Controller\ShopController::showForm
    defaults:
        id: null

create_shop:
    path: /tienda/crear
    controller: App\Controller\ShopController::create
    methods: POST

update_shop:
    path: /tienda/actualizar/{id}
    controller: App\Controller\ShopController::update
    methods: [POST]

delete_shop:
    path: /tienda/eliminar/{id}
    controller: App\Controller\ShopController::delete
    methods: [GET]

login:
    path: /login
    controller: App\Controller\SecurityController::loginAction

    