home:
    path: adminlte_welcome
# Employees
index:
    path: /
    controller: App\Controller\EmployeeController::index

list_employees:
    path: /empleado/lista
    controller: App\Controller\EmployeeController::index

show_form:
    path: /empleado/registro/{id}
    controller: App\Controller\EmployeeController::showForm
    defaults:
        id: null

create_employee:
    path: /empleado/crear
    controller: App\Controller\EmployeeController::create
    methods: POST

update_employee:
    path: /empleado/actualizar/{id}
    controller: App\Controller\EmployeeController::update
    methods: [POST]

delete_employee:
    path: /empleado/eliminar/{id}
    controller: App\Controller\EmployeeController::delete
    methods: [GET]

# Customers   
list_customer:
    path: /cliente/lista
    controller: App\Controller\CustomerController::index

show_form_customer:
    path: /cliente/registro/{id}
    controller: App\Controller\CustomerController::showForm
    defaults:
        id: null

create_customer:
    path: /cliente/crear
    controller: App\Controller\CustomerController::create
    methods: POST

update_customer:
    path: /cliente/actualizar/{id}
    controller: App\Controller\CustomerController::update
    methods: [POST]

delete_customer:
    path: /cliente/eliminar/{id}
    controller: App\Controller\CustomerController::delete
    methods: [GET]


#ShopGroups
list_shopgroup:
    path: /shopgroup/list
    controller: App\Controller\ShopGroupController::index
#Shops
list_shop:
    path: /tienda/lista
    controller: App\Controller\ShopController::index

show_form_shop:
    path: /tienda/registro/{id}
    controller: App\Controller\ShopController::showForm
    defaults:
        id: null

create_shop:
    path: /tienda/crear
    controller: App\Controller\ShopController::create
    methods: POST

update_shop:
    path: /tienda/actualizar/{id}
    controller: App\Controller\ShopController::update
    methods: [POST]

delete_shop:
    path: /tienda/eliminar/{id}
    controller: App\Controller\ShopController::delete
    methods: [GET]

list_product:
    path: /product/list
    controller: App\Controller\ProductController::index

login:
    path: /login
    controller: App\Controller\SecurityController::loginAction

    