home:
    path: adminlte_welcome
# Employees
index:
    path: /
    controller: App\Controller\EmployeeController::index

list_employees:
    path: /admin/empleado/lista
    controller: App\Controller\EmployeeController::index

show_form:
    path: /admin/empleado/registro/{id}
    controller: App\Controller\EmployeeController::showForm
    defaults:
        id: null

create_employee:
    path: /admin/empleado/crear
    controller: App\Controller\EmployeeController::create
    methods: POST

update_employee:
    path: /admin/empleado/actualizar/{id}
    controller: App\Controller\EmployeeController::update
    methods: [POST]

delete_employee:
    path: /admin/empleado/eliminar/{id}
    controller: App\Controller\EmployeeController::delete
    methods: [GET]

# Customers   
list_customer:
    path: /admin/cliente/lista
    controller: App\Controller\CustomerController::index

show_form_customer:
    path: /admin/cliente/registro/{id}
    controller: App\Controller\CustomerController::showForm
    defaults:
        id: null

create_customer:
    path: /admin/cliente/crear
    controller: App\Controller\CustomerController::create
    methods: POST

update_customer:
    path: /admin/cliente/actualizar/{id}
    controller: App\Controller\CustomerController::update
    methods: [POST]

delete_customer:
    path: /admin/cliente/eliminar/{id}
    controller: App\Controller\CustomerController::delete
    methods: [GET]

#Products
list_product:
    path: /admin/productos/lista
    controller: App\Controller\ProductController::index

show_form_product:
    path: /admin/producto/registro/{id}
    controller: App\Controller\ProductController::showForm
    defaults:
        id: null

create_product:
    path: /admin/producto/crear
    controller: App\Controller\ProductController::create
    methods: POST

update_product:
    path: /admin/producto/actualizar/{id}
    controller: App\Controller\ProductController::update
    methods: [POST]

delete_product:
    path: /admin/producto/eliminar/{id}
    controller: App\Controller\ProductController::delete
    methods: [GET]

#ShopGroups
list_shopgroup:
    path: /admin/shopgroup/lista
    controller: App\Controller\ShopGroupController::index

show_form_shopgroup:
    path: /admin/shopgroup/registro/{id}
    controller: App\Controller\ShopGroupController::showForm
    defaults:
        id: null

create_shopgroup:
    path: /admin/shopgroup/crear
    controller: App\Controller\ShopGroupController::create
    methods: POST

update_shopgroup:
    path: /admin/shopgroup/actualizar/{id}
    controller: App\Controller\ShopGroupController::update
    methods: [POST]

delete_shopgroup:
    path: /admin/shopgroup/eliminar/{id}
    controller: App\Controller\ShopGroupController::delete
    methods: [GET]

#ShopSeries
list_shopseries:
    path: /admin/shopseries/lista
    controller: App\Controller\ShopSeriesController::index

show_form_shopseries:
    path: /admin/shopseries/registro/{id}
    controller: App\Controller\ShopSeriesController::showForm
    defaults:
        id: null

create_shopseries:
    path: /admin/shopseries/crear
    controller: App\Controller\ShopSeriesController::create
    methods: POST

update_shopseries:
    path: /admin/shopseries/actualizar/{id}
    controller: App\Controller\ShopSeriesController::update
    methods: [POST]

delete_shopseries:
    path: /admin/shopseries/eliminar/{id}
    controller: App\Controller\ShopSeriesController::delete
    methods: [GET]

#Shops
list_shop:
    path: /admin/tienda/lista
    controller: App\Controller\ShopController::index

show_form_shop:
    path: /admin/tienda/registro/{id}
    controller: App\Controller\ShopController::showForm
    defaults:
        id: null

create_shop:
    path: /admin/tienda/crear
    controller: App\Controller\ShopController::create
    methods: POST

update_shop:
    path: /admin/tienda/actualizar/{id}
    controller: App\Controller\ShopController::update
    methods: [POST]

delete_shop:
    path: /admin/tienda/eliminar/{id}
    controller: App\Controller\ShopController::delete
    methods: [GET]



#Sales
list_sales:
    path: /admin/ventas/lista
    controller: App\Controller\SaleController::index

show_form_sale:
    path: /admin/venta/registro/{id}
    controller: App\Controller\SaleController::showForm
    defaults:
        id: null

create_sale:
    path: /admin/venta/crear
    controller: App\Controller\SaleController::create
    methods: POST

update_sale:
    path: /admin/venta/actualizar/{id}
    controller: App\Controller\SaleController::update
    methods: [POST]

delete_sale:
    path: /admin/venta/eliminar/{id}
    controller: App\Controller\SaleController::delete
    methods: [GET]




    